[[plugins]]
package = "@algolia/netlify-plugin-crawler"
    [plugins.inputs]
    branches = ['main']
    disabled = true
    pathPrefix = "/docs"
    customDomain = "hiro.so"
    renderJavaScript = true